# Generated by Django 4.0.1 on 2023-10-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
