# Generated by Django 4.0.1 on 2023-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shippingaddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
